#!/usr/bin/env python3

import os
import sys
from utils.confirm import confirm

def main():
  folder = sys.argv[1]
  target_name = sys.argv[2]
  i = 0

  print('Files to rename:')
  for file in os.listdir(folder):
    print(file)
  if not confirm():
    exit()

  for file in os.listdir(folder):
    src = os.path.join(folder, file)
    file_extension = os.path.splitext(src)[1]

    if (i > 0):
      full_target_name = f'{target_name}-{i + 1}'
    else:
      full_target_name = target_name

    full_target_name += file_extension

    dst = os.path.join(folder, full_target_name)
    os.rename(src, dst)
    i += 1

main()
