#!/usr/bin/env python3

print('git branch-clear', '-' 'Deletes all local branches')
print('git branch-alias <alias> <branch>', '-', 'Creates an alias for chosen branch')
print('rename-files <path> <new_name>', '-', 'Renames all files in directory to passed name')
